name: vpn
services:
  ### Virtual Private Network ###
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 6767:6767 # Bazarr
      - 8191:8191 # FlareSolverr
      - 8080:8080 # qBittorrent (Web UI)
      - 6881:6881 # qBittorrent (Torrent)
      - 6881:6881/udp # qBittorrent (Torrent/UDP)
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_TYPE=${VPN_Type}
      - TZ=${Device_Timezone}
      - SERVER_CITIES=Toronto
      - OPENVPN_USER=${VPN_Username}
      - OPENVPN_PASSWORD=${VPN_Password}
      - VPN_SERVICE_PROVIDER=${VPN_Provider}
    volumes:
      - /home/zach/docker/config/vpn:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun

  ### Indexer Management ###
  Prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: Prowlarr
    network_mode: "service:vpn"
    restart: unless-stopped
    environment:
      - TZ=${Device_Timezone}
      - PUID=${Device_UserID}
      - PGID=${Device_GroupID}
    volumes:
      - /home/zach/docker/config/Prowlarr:/config

  ### TV Show Management ###
  Sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: Sonarr
    network_mode: "service:vpn"
    restart: unless-stopped
    environment:
      - TZ=${Device_Timezone}
      - PUID=${Device_UserID}
      - PGID=${Device_GroupID}
    volumes:
      - /mnt/Drive16/Shows:/tv
      - /mnt/Drive16/Downloads:/downloads
      - /home/zach/docker/config/Sonarr:/config

  ### Movie Management ###
  Radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: Radarr
    network_mode: "service:vpn"
    restart: unless-stopped
    environment:
      - TZ=${Device_Timezone}
      - PUID=${Device_UserID}
      - PGID=${Device_GroupID}
    volumes:
      - /mnt/Drive16/Movies:/movies
      - /mnt/Drive16/Downloads:/downloads
      - /home/zach/docker/config/Radarr:/config

  ### Subtitle Management ###
  Bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: Bazarr
    network_mode: "service:vpn"
    restart: unless-stopped
    environment:
      - TZ=${Device_Timezone}
      - PUID=${Device_UserID}
      - PGID=${Device_GroupID}
    volumes:
      - /mnt/Drive16/Shows:/tv
      - /mnt/Drive16/Movies:/movies
      - /home/zach/docker/config/Bazarr:/config

  ### Cloudflare Bypass ###
  FlareSolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: FlareSolverr
    network_mode: "service:vpn"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${Device_Timezone}

  ### Torrent Management ###
  qBittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qBittorrent
    network_mode: "service:vpn"
    restart: unless-stopped
    environment:
      - TZ=${Device_Timezone}
      - PUID=${Device_UserID}
      - PGID=${Device_GroupID}
      - WEBUI_PORT=${WebUI_Port}
      - TORRENTING_PORT=${Torrent_Port}
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /mnt/Drive16/Downloads:/downloads
      - /home/zach/docker/config/qBittorrent:/config