name: system
services:
  ### --- Container - Management --- ###
  Portainer:
    image: portainer/portainer-ce:latest
    container_name: Portainer
    network_mode: bridge
    restart: always
    ports:
      - 9443:9443
    environment:
      - TZ=${Device_Timezone}
      - PUID=${Device_UserID}
      - PGID=${Device_GroupID}
    volumes:
      - /home/zach/docker/config/Portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  ### --- System - Monitor --- ###
  Glances:
    image: nicolargo/glances:ubuntu-latest-full
    container_name: Glances
    network_mode: host
    restart: unless-stopped
    privileged: true
    pid: host
    ports:
      - 61208:61208
      - 61209:61209
    environment:
      - GLANCES_OPT=-w
      - TZ=${Device_Timezone}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro

  ### --- Cloudflare - Tunnel --- ###
  Cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: Cloudflared
    network_mode: bridge
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${Cloudflared_Token}

  ### --- Container Log - Monitor --- ###
  Dozzle:
    image: amir20/dozzle:latest
    container_name: Dozzle
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 9998:8080
    environment:
      - TZ=${Device_Timezone}
      - PUID=${Device_UserID}
      - PGID=${Device_GroupID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock