name: monitor
services:
  ### --- Jellyfin Sync - Update Monitor --- ###
  JellyPlex-Watched:
    image: luigi311/jellyplex-watched:latest
    container_name: JellyPlex-Watched
    network_mode: bridge
    restart: unless-stopped
    environment:
      - TZ=${Device_Timezone}
      - PUID=${Device_UserID}
      - PGID=${Device_GroupID}
    volumes:
      - /home/zach/docker/config/JellyPlex-Watched/.env:/app/.env

  ### --- Container - Update Monitor --- ###
  WatchTower:
    image: containrrr/watchtower:latest
    container_name: WatchTower
    network_mode: bridge
    restart: unless-stopped
    environment:
      - TZ=${Device_Timezone}
      - PUID=${Device_UserID}
      - PGID=${Device_GroupID}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LOG_LEVEL=info
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_NOTIFICATION_REPORT=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock