# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/json-schema/config-schema.json

#==================== Libraries ====================#
libraries:
  Movies Overlay:
    library_name: Movies
    schedule: daily
    remove_overlays: false
    reapply_overlays: false
    overlay_files:
      # Media information : Resolution, HDR and HD audio
      - file: /config/media_info.yml

      # Rating Only
      - file: /config/audience_rating.yml

      # MULTi Audio Flag
      - default: languages
        template_variables:
          languages:
            - en
          use_subtitles: false
          file: /config/images/flags/<<key>>.png
          text: " "
          back_width: 40
          back_height: 80
          back_color: "#FFFFFF00"
          horizontal_offset: 180
          horizontal_align: right
          vertical_offset: 50
          vertical_align: bottom

  TV Shows Overlay:
    library_name: TV Shows
    schedule: daily
    remove_overlays: false
    reapply_overlays: false
    overlay_files:
      # Media information : Resolution, HDR and HD audio
      - file: /config/media_info.yml

      # Rating Only
      - file: /config/audience_rating.yml

      # MULTi Audio Flag
      - default: languages
        template_variables:
          languages:
            - en
          use_subtitles: false
          file: /config/images/flags/<<key>>.png
          text: " "
          back_width: 40
          back_height: 80
          back_color: "#FFFFFF00"
          horizontal_offset: 180
          horizontal_align: right
          vertical_offset: 50
          vertical_align: bottom

      # Series Status : Ended, Returning, etc
      - default: status
        template_variables:
          text_airing: " "
          file_airing: /config/images/media_info/status/airing.png
          text_returning: " "
          file_returning: /config/images/media_info/status/returning.png
          text_canceled: " "
          file_canceled: /config/images/media_info/status/canceled.png
          text_ended: " "
          file_ended: /config/images/media_info/status/ended.png
          vertical_align: top
          horizontal_align: center
          vertical_offset: 40
          horizontal_offset: 170
          back_width_airing: 1100
          back_width_returning: 1100
          back_width_ended: 1100
          back_width_cancelled: 1100
          back_color: '#FFFFFF00'

#==================== Settings ====================#
settings:
  ignore_ids:
  cache: true
  cache_expiration: 60
  show_missing_assets: true
  asset_directory: /assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: true
  show_missing_episode_assets: true
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: false
  save_report: false
  tvdb_language: eng
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  run_order:
    - overlays

  show_unfiltered: false
  playlist_sync_to_users:
  overlay_artwork_filetype: png
  overlay_artwork_quality: 90
webhooks:
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:

#==================== Plex ====================#
plex:
  url: http://<DEVICE IP>:32400
  token: <PLEX TOKEN>
  timeout: 60
  db_cache: 10240
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl: false

#==================== TMDb ====================#
tmdb:
  apikey: <TMDB API KEY>
  language: en
  cache_expiration: 60
  region: ''