- Statistics:
    - CPU:
        icon: /images/SystemInfo.png
        href: https://stats.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        widget:
          type: glances
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:61208
          metric: cpu
          version: 4
          chart: false
    - Memory:
        icon: /images/Memory.png
        href: https://stats.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        widget:
          type: glances
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:61208
          metric: memory
          version: 4
          chart: false
    - Processes:
        icon: /images/CPU.png
        href: https://stats.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        widget:
          type: glances
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:61208
          metric: process
          version: 4
          chart: true
    - Harddrive:
        icon: /images/LinuxDrive.png
        href: https://stats.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        widget:
          type: glances
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:61208
          metric: fs:/etc/hosts
          version: 4
          chart: false
- Media Services:
    - Plex:
        icon: plex.svg
        href: https://plex.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: Primary Media Server
        server: MurphyServer
        container: Plex
        widget:
          type: plex
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:32400
          key: "{{HOMEPAGE_VAR_PLEX_API}}"
          fields: ["albums", "movies", "tv"]
    - qBittorrent:
        icon: qbittorrent.svg
        href: https://qbit.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: Torrent Downloader
        server: MurphyServer
        container: qBittorrent
        widget:
          type: qbittorrent
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:8080
          username: "{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}"
          password: "{{HOMEPAGE_VAR_QBITTORRENT_PWD}}"
          enableLeechProgress: true
          fields: ["seed", "download", "upload"]
- Monitoring:
    - Tautulli:
        icon: tautulli.svg
        href: https://tautulli.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: Streaming Information
        server: MurphyServer
        container: Tautulli
        widget:
          type: tautulli
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:8181
          key: "{{HOMEPAGE_VAR_TAUTULLI_API}}"
          enableUser: false
          showEpisodeNumber: true
          expandOneStreamToTwoRows: true
    - Portainer:
        icon: portainer.svg
        href: https://portainer.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: Docker Container Management
        server: MurphyServer
        container: Portainer
        widget:
          type: portainer
          url: https://{{HOMEPAGE_VAR_LOCAL_IP}}:9443
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER_API}}"
    - Speedtest:
        icon: speedtest-tracker.png
        href: https://speedtest.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: Network Speed Results
        container: Speedtest
        widget:
          type: speedtest
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:2255
          bitratePrecision: 2
    - Cloudflared:
        icon: cloudflare.png
        href: https://cloudflare.com
        description: Remote Access
        server: MurphyServer
        container: Cloudflared
        widget:
          type: cloudflared
          accountid: "{{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}"
          tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}}"
          key: "{{HOMEPAGE_VAR_CLOUDFLARE_TOKEN_ID}}"
          fields: ["status"]
- Arrs Services:
    - TV Show Sonarr:
        icon: sonarr.svg
        href: https://sonarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: TV Show Organizer
        server: MurphyServer
        container: Sonarr
        widget:
          type: sonarr
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:8989
          key: "{{HOMEPAGE_VAR_SONARR_API}}"
    - Radarr:
        icon: radarr.svg
        href: https://radarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: Movies Organizer
        server: MurphyServer
        container: Radarr
        widget:
          type: radarr
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:7878
          key: "{{HOMEPAGE_VAR_RADARR_API}}"
          fields: ["wanted", "queued", "movies"]
    - Overseerr:
        icon: overseerr.svg
        href: https://overseerr.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: Media Request
        server: MurphyServer
        container: Overseerr
        widget:
          type: overseerr
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:5055
          key: "{{HOMEPAGE_VAR_OVERSEERR_API}}"
          fields: ["pending", "available", "processing"]
    - Bazarr:
        icon: cc-light.png
        href: https://bazarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: Subtitles Manager
        server: MurphyServer
        container: Bazarr
        widget:
          type: bazarr
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:6767
          key: "{{HOMEPAGE_VAR_BAZARR_API}}"
          fields: ["missingEpisodes", "missingMovies"]
- Management:
    - Dozzle:
        icon: dozzle.svg
        href: https://dozzle.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: Docker Container Log Viewer
        server: MurphyServer
        container: Dozzle
    - Spotify Downloader:
        icon: spotify.png
        href: https://spotify.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
        description: Download Spotify Music
        server: MurphyServer
        container: Spotify
- Calendars:
    - Upcoming TV Shows:
        icon: sonarr.svg
        widget:
          type: calendar
          firstDayInWeek: monday
          view: agenda
          maxEvents: 8
          showTime: true
          integrations:
            - type: ical
              url: https://sonarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}/feed/v3/calendar/Sonarr.ics?apikey={{HOMEPAGE_VAR_SONARR_API}}
              name: TV Shows
              color: orange
              params:
                showName: false

    ##################################################################################
    ###                                Shows                                       ###
    ##################################################################################
    - Recently Added Shows:
        icon: sonarr.svg
        id: list
        widget:
          type: customapi
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:8181/api/v2?apikey={{HOMEPAGE_VAR_TAUTULLI_API}}&cmd=get_recently_added&count=6&media_type=episode&section_id=3
          display: list
          mappings:
            - field:
                response:
                  data:
                    recently_added:
                      0: grandparent_title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        0: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme
            - field:
                response:
                  data:
                    recently_added:
                      1: grandparent_title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        1: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme
            - field:
                response:
                  data:
                    recently_added:
                      2: grandparent_title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        2: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme
            - field:
                response:
                  data:
                    recently_added:
                      3: grandparent_title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        3: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme
            - field:
                response:
                  data:
                    recently_added:
                      4: grandparent_title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        4: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme
            - field:
                response:
                  data:
                    recently_added:
                      5: grandparent_title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        5: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme

    ##################################################################################
    ###                               Movies                                       ###
    ##################################################################################
    - Recently Added Movies:
        icon: radarr.svg
        id: list
        widget:
          type: customapi
          url: http://{{HOMEPAGE_VAR_LOCAL_IP}}:8181/api/v2?apikey={{HOMEPAGE_VAR_TAUTULLI_API}}&cmd=get_recently_added&count=6&media_type=movie
          display: list
          mappings:
            - field:
                response:
                  data:
                    recently_added:
                      0: title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        0: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme
            - field:
                response:
                  data:
                    recently_added:
                      1: title
              color: theme
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        1: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme
            - field:
                response:
                  data:
                    recently_added:
                      2: title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        2: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme
            - field:
                response:
                  data:
                    recently_added:
                      3: title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        3: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme
            - field:
                response:
                  data:
                    recently_added:
                      4: title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        4: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme
            - field:
                response:
                  data:
                    recently_added:
                      5: title
              additionalField:
                field:
                  response:
                    data:
                      recently_added:
                        5: added_at
                scale: 1000
                format: relativeDate
                locale: en-GB
                numeric: auto
                style: narrow
                color: theme