name: services
services:
  ### --- Jellyfin - Media Server --- ###
  Jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: Jellyfin
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${Device_Timezone}
      - PUID=${Device_UserID}
      - PGID=${Device_GroupID}
      - JELLYFIN_PublishedServerUrl=${Jellyfin_PublishedServer}
    volumes:
      - /mnt/Drive20/Music:/data/music
      - /mnt/Drive20/TV Shows:/data/tv
      - /mnt/Drive20/Movies:/data/movies
      - /mnt/Drive20/Pre-Rolls:/data/pre-rolls
      - /home/zach/docker/config/Jellyfin:/config
      - /home/zach/docker/config/Jellyfin-Cache:/cache
    extra_hosts:
      - host.docker.internal:host-gateway
    devices:
      - /dev/dri:/dev/dri

  ### --- Open Source - Password Manager --- ###
  VaultWarden:
    image: vaultwarden/server:latest
    container_name: VaultWarden
    network_mode: host
    restart: unless-stopped
    environment:
      - DOMAIN=${VaultWarden_Domain}
      - ROCKET_PORT=${VaultWarden_Port}
      - ADMIN_TOKEN=${VaultWarden_AdminToken}
      - ICON_SERVICE=${VaultWarden_IconService}
      - SIGNUPS_ALLOWED=${VaultWarden_Register}
      - WEB_VAULT_ENABLED=${VaultWarden_WebVault}
      - DISABLE_ICON_DOWNLOAD=${VaultWarden_DisableIcon}
      - EMERGENCY_ACCESS_ALLOWED=${VaultWarden_EmergencyAccess}
    volumes:
      - /home/zach/docker/config/VaultWarden/:/data/

  ### --- Open Source - Git Platform --- ###
  Forgejo:
    image: codeberg.org/forgejo/forgejo:10
    container_name: Forgejo
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 222:22
      - 3000:3000
    environment:
      - USER_UID=${Device_UserID}
      - USER_GID=${Device_GroupID}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/zach/docker/config/Forgejo:/data